services:
  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      JWT_SECRET: change-me-in-prod-use-at-least-32-bytes-secret-key
      CORE_URI: http://localhost:8081
    ports:
      - "8088:8088"