server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: coreRoute
              uri: ${CORE_URI:http://localhost:8081}
              predicates:
                - Path=/api/profiles/**,/api/auth/**,/api/matching/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 10
                      burstCapacity: 20
                      requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: coreCircuitBreaker
                    fallbackUri: forward:/fallback/core
            - id: matchingRoute
              uri: ${MATCHING_URI:http://localhost:8083}
              predicates:
                - Path=/api/recommendations/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 10
                      burstCapacity: 20
                      requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: matchingCircuitBreaker
                    fallbackUri: forward:/fallback/matching

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}

resilience4j:
  circuitbreaker:
    instances:
      coreCircuitBreaker:
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 4000ms
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 60s
#      пока что копия core, сделано для индивидуальной настройки в будущем
      matchingCircuitBreaker:
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 4000ms
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 60s
        
  timelimiter:
    instances:
      coreCircuitBreaker:
        timeoutDuration: 8s
      matchingCircuitBreaker:
        timeout-duration: 8s

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - gateway

app:
  jwt:
    secret: ${JWT_SECRET:change-me-in-prod-use-at-least-32-bytes-secret-key}